<a href="https://colab.research.google.com/github/ZvoneST/pytorch-labs/blob/master/Autodef_lovro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Automatic differentiation

## Pyforest
Writing the same imports over and over again is below your capacity. Let pyforest do the job for you.

With pyforest you can use all your favorite Python libraries without importing them before. If you use a package that is not imported yet, pyforest imports the package for you and adds the code to the first Jupyter cell. If you don't use a library, it won't be imported.

As this is not a library that automatically comes with Google Colab, we will use the Linux pip command to install the required library.

In [ ]:
!pip install pyforest

  Created wheel for pyforest: filename=pyforest-1.1.0-py2.py3-none-any.whl size=14607 sha256=4f0a9aac8bcc2953e6d40cf63fa195657f02664dd27c0e562aff5e4c3d0c4825
  Stored in directory: /root/.cache/pip/wheels/61/1c/da/48e6c884142d485475d852d69d20a096aba5beceb338822893
Successfully built pyforest


In [ ]:
import pyforest

After you installed pyforest and its Jupyter extension, you can use your favorite Python Data Science commands like you normally would - just without writing imports.<br> Example np.array()

In [ ]:
np.array([1, 2, 3])

<IPython.core.display.Javascript object>

array([1, 2, 3])

In [ ]:
a = torch.tensor([7.], requires_grad = True)
b = torch.tensor([5.], requires_grad = True)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
print(a)

tensor([7.], requires_grad=True)


In [ ]:
y = a**3 + 8*b
#3a**2 + 8

In [ ]:
y

tensor([383.], grad_fn=<AddBackward0>)

In [ ]:
y.backward()

In [ ]:
b.grad

tensor([8.])

Why is b.grad 8?
The idea is to derive the function $y$ so that a is viewed as some fixed number (some constant).
$$y=a^3+8b$$
$$ \frac{\partial y}{\partial b} = 8$$
$a^3$ we look as a constant, a we know that derivative of constant is 0, and we know that derivtive of $8b$ is 8.<br>

For all those who do not know or have forgotten the derivation tables ...
<img src = "https://i.pinimg.com/474x/b7/a0/8d/b7a08d80f4f276f6360ef23633fb6fd8.jpg">

In [ ]:
a.grad

tensor([147.])

$$y=a^3+8b$$
$$ \frac{\partial y}{\partial a} = 3a^2 = 3\cdot7^2=3\cdot49=147$$